FROM node:20                           

WORKDIR /app
COPY package.json package-lock.json ./ 

RUN npm i && npm run build                              

COPY  . .                              
EXPOSE  3000                           
CMD [ "npm","run","start" ]              

